language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"
install: pip install nose
script:
  - python setup.py test
notifications:
  irc:
    channels: "irc.freenode.org#pip"
    on_success: change
    on_failure: change
